/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_yidafu_swc_binding_SwcNative */

#ifndef _Included_dev_yidafu_swc_binding_SwcNative
#define _Included_dev_yidafu_swc_binding_SwcNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_yidafu_swc_binding_SwcNative
 * Method:    sayHello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_dev_yidafu_swc_binding_SwcNative_sayHello
  (JNIEnv *, jobject, jstring);

/*
 * Class:     dev_yidafu_swc_binding_SwcNative
 * Method:    runSwc
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_dev_yidafu_swc_binding_SwcNative_runSwc
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
