/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/8.0.2/userguide/building_java_projects.html
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    id("dev.yidafu.library")
//    alias(libs.plugins.jvm)
    alias(libs.plugins.jupyter)
    alias(libs.plugins.ksp)
//    alias(libs.plugins.publisher)
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.kover)

    `maven-publish`
}

kotlin {
    jvmToolchain(19)
}

kotlinJupyter {
    addApiDependency()
    // addScannerDependency() - Removed in Kotlin Jupyter API 0.16.0+
}

// Creates the metadata needed for the library integration to be detected automatically.
tasks.processJupyterApiResources {
    libraryProducers = listOf("dev.yidafu.jupyper.KotlinKernelJsMagicSupport")
}

group = "dev.yidafu.jupyter"
version = "0.8.0"

dependencies {
    implementation(libs.dokka.analysis.compiler)
    testImplementation(kotlin("test"))
    implementation(libs.slf4j.api)
    implementation(libs.kotlin.serialization.json)
    implementation(libs.swc.binding)

    testImplementation(libs.bundles.kotest)
    testImplementation(libs.mockk)
}

repositories {
    mavenLocal()
    maven("https://mirrors.cloud.tencent.com/nexus/repository/maven-public")
    maven("https://s01.oss.sonatype.org/content/groups/public/")
    mavenCentral()
}

publishMan {
    name.set("Kotlin Jupyter JS Support")
    description.set("Kotlin Jupyter JS Support")
}

// 配置本地发布，禁用签名
publishing {
    publications {
        create<MavenPublication>("maven") {
            from(components["java"])

            pom {
                name.set("Kotlin Jupyter JS Support")
                description.set("Kotlin Jupyter JS Support")
                url.set("https://github.com/yidafu/kotlin-jupyter-js/")

                licenses {
                    license {
                        name.set("The Apache License, Version 2.0")
                        url.set("http://www.apache.org/licenses/LICENSE-2.0.txt")
                    }
                }

                developers {
                    developer {
                        id.set("dovyih")
                        name.set("Dov Yih")
                        email.set("me@yidafu.dev")
                    }
                }

                scm {
                    connection.set("scm:git:git://github.com:yidafu/kotlin-jupyter-js.git")
                    developerConnection.set("scm:git:ssh://github.com:yidafu/kotlin-jupyter-js.git")
                    url.set("https://github.com:yidafu/kotlin-jupyter-js/")
                }
            }
        }
    }
}

// 禁用签名任务
tasks.withType<Sign> {
    enabled = false
}

tasks.withType<Test>().configureEach {
    useJUnitPlatform()
}

// Optionally configure plugin
configure<org.jlleitschuh.gradle.ktlint.KtlintExtension> {
    debug.set(true)
    version.set("1.1.1")
    disabledRules.set(setOf("standard:no-wildcard-imports", "standard:filename"))
}
