/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/8.0.2/userguide/multi_project_builds.html
 * This project uses @Incubating APIs which are subject to change.
 */

pluginManagement {
    repositories {
        mavenLocal()

        maven("https://mirrors.cloud.tencent.com/nexus/repository/maven-public")
        maven("https://s01.oss.sonatype.org/content/groups/public/")
        gradlePluginPortal()
        mavenCentral()
    }
}

enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")

dependencyResolutionManagement {
    versionCatalogs {
        create("libs") {
            from(files("./build-plugin/libs.versions.toml"))
        }
    }
}

includeBuild("build-plugin")

rootProject.name = "kotlin-notebook-js"

include("jupyter-js")
project(":jupyter-js").name = "jupyter-js"
