/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package dev.yidafu.jupyter

import org.jetbrains.kotlinx.jupyter.api.HTML
import org.jetbrains.kotlinx.jupyter.api.annotations.JupyterLibrary
import org.jetbrains.kotlinx.jupyter.api.libraries.JupyterIntegration
import org.slf4j.Logger
import org.slf4j.LoggerFactory

/**
 * support `%javascript` magic
 */
@JupyterLibrary
class KotlinKernelJsMagicSupport : JupyterIntegration() {
    val log: Logger = LoggerFactory.getLogger(KotlinKernelJsMagicSupport::class.java)

    override fun Builder.onLoaded() {
        import(
            "dev.yidafu.jupyter.jsExport",
        )
        onLoaded {
            JavaScriptVariableStore.clear()

            display(JavaScriptImportMap(), "jupyter-js-importmap")
        }

        addCodePreprocessor(JavaScriptMagicCodeProcessor(this.notebook))
    }
}
