/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package dev.yidafu.jupyper

import org.jetbrains.kotlinx.jupyter.api.annotations.JupyterLibrary
import org.jetbrains.kotlinx.jupyter.api.libraries.JupyterIntegration
import org.slf4j.LoggerFactory

/**
 * support `%javascript` magic
 */
@JupyterLibrary
class KotlinKernelJsMagicSupport : JupyterIntegration() {
    val log = LoggerFactory.getLogger(KotlinKernelJsMagicSupport::class.java)

    override fun Builder.onLoaded() {
        import(
            "dev.yidafu.jupyper.jsExport",
        )
        onLoaded {
            JavaScriptVariableStore.clear()
        }

        addCodePreprocessor(JavaScriptMagicCodeProcessor(this.notebook))
    }
}
