/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package dev.yidafu.jupyper

import dev.yidafu.swc.SwcNative
import org.jetbrains.kotlinx.jupyter.api.annotations.JupyterLibrary
import org.jetbrains.kotlinx.jupyter.api.libraries.JupyterIntegration
import org.slf4j.LoggerFactory

/**
 * support `%javascript` magic
 */
@JupyterLibrary
class KotlinKernelJsSupport : JupyterIntegration() {
    val log = LoggerFactory.getLogger(KotlinKernelJsSupport::class.java)

    override fun Builder.onLoaded() {
        import<JsCodeResult>()
        import<SwcNative>()
        import(
            "dev.yidafu.swc.dsl.*",
            "dev.yidafu.swc.types.*",
            "dev.yidafu.swc.*",
        )

        addCodePreprocessor(JavaScriptMagicCodeProcessor())
    }
}
