/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package dev.yidafu.jupyper

import org.jetbrains.kotlinx.jupyter.api.ProcessingPriority
import org.jetbrains.kotlinx.jupyter.api.annotations.JupyterLibrary
import org.jetbrains.kotlinx.jupyter.api.libraries.JupyterIntegration

/**
 * support `%javascript` magic
 */
@JupyterLibrary
class KotlinKernelJsSupport : JupyterIntegration() {
    override fun Builder.onLoaded() {
//        this.notebook.codePreprocessorsProcessor.register(JavaScriptMagicCodeProcessor(), ProcessingPriority.HIGHEST)
//        beforeCellExecution {
//
//        }
        addCodePreprocessor(JavaScriptMagicCodeProcessor())
    }
}
